### ISSUE TITLE
Installation failed (Errors were encountered while processing:  open-as-cgw  sa-compile E: Sub-process /usr/bin/dpkg returned an error code (1))

### ISSUE THREAD

**Issue by schallertd** [open-as-team/open-as-cgw#7]
Hello,

Looking to get OpenAS setup, and got the following output when installing. 

As per the message, I'm opening a ticket here with the console output and log files. 

Let me know if any further details are needed. 

Thanks,

Jon

Launchpad Details: [#LP1554212](https://bugs.launchpad.net/bugs/1554212) Jonathan Halewood - 2016-03-07 20:41:23 +0000

**Comment by dschallert** [comment]
Thanks for the report.

The issue seems to occur with spamassasin while compiling the ruleset. 
We could not reproduce it so far.

	Running sa-compile (may take a long time)
	command 'make install >>/tmp/.spamassassin31659gUqPovtmp/log' failed: exit 0
	dpkg: error processing package sa-compile (--configure):
	subprocess installed post-installation script returned error exit status 12

Referencing ticket @SA - https://bugs.launchpad.net/ubuntu/+source/spamassassin/+bug/1327004

Will investigate that within the next days.


Thanks

Launchpad Details: [#LPC](https://bugs.launchpad.net/open-as-cgw/+bug/1554212/comments/5) Dominic Schallert - 2016-06-18 13:15:57 +0000

**Comment by schallertd** [comment]
Fixed with https://github.com/open-as-team/open-as-cgw/commit/d7d45c4e235d34c21032a3e99c8da3b94c045c56
